name: coinos-base
description: A lightweight OS for deploying and running algorithmic trading systems.
base: bookworm

packages:
  - raspberrypi-kernel
  - raspberrypi-bootloader
  - network-manager
  - openssh-server
  - python3
  - git
  - curl
  - vim